#!/bin/sh

# Provider adapter for Entware 3proxy + SSLPlugin + PCREPlugin.
# The adapter intentionally supports explicit-proxy mode only; it never creates
# iptables/NAT rules and therefore cannot silently redirect household HTTPS.

https_3proxy_find_bin()
{
    if [ -n "${HTTPS_3PROXY_BIN:-}" ] && [ -x "$HTTPS_3PROXY_BIN" ]; then printf '%s\n' "$HTTPS_3PROXY_BIN"; return 0; fi
    for p in /opt/bin/3proxy /opt/sbin/3proxy /usr/bin/3proxy /usr/sbin/3proxy; do [ -x "$p" ] && { printf '%s\n' "$p"; return 0; }; done
    return 1
}

https_3proxy_find_plugin()
{
    https_fp_name="$1"; https_fp_override="$2"
    [ -n "$https_fp_override" ] && [ -r "$https_fp_override" ] && { printf '%s\n' "$https_fp_override"; return 0; }
    for p in \
        "/opt/lib/3proxy/${https_fp_name}.ld.so" \
        "/opt/lib/3proxy/${https_fp_name}.so" \
        "/opt/lib/3proxy/plugins/${https_fp_name}.ld.so" \
        "/opt/lib/3proxy/plugins/${https_fp_name}.so" \
        "/usr/lib/3proxy/plugins/${https_fp_name}.ld.so" \
        "/usr/lib/3proxy/plugins/${https_fp_name}.so"; do
        [ -r "$p" ] && { printf '%s\n' "$p"; return 0; }
    done
    return 1
}

https_3proxy_find_upstream_ca()
{
    if [ -n "${HTTPS_UPSTREAM_CA_FILE:-}" ] && [ -r "$HTTPS_UPSTREAM_CA_FILE" ]; then printf '%s\n' "$HTTPS_UPSTREAM_CA_FILE"; return 0; fi
    for p in /opt/etc/ssl/certs/ca-certificates.crt /opt/etc/ssl/cert.pem /etc/ssl/certs/ca-certificates.crt /etc/ssl/cert.pem; do
        [ -r "$p" ] && { printf '%s\n' "$p"; return 0; }
    done
    return 1
}

https_3proxy_probe()
{
    HTTPS_3PROXY_BIN_RESOLVED="$(https_3proxy_find_bin 2>/dev/null || true)"
    HTTPS_SSL_PLUGIN_RESOLVED="$(https_3proxy_find_plugin SSLPlugin "${HTTPS_SSL_PLUGIN:-}" 2>/dev/null || true)"
    HTTPS_PCRE_PLUGIN_RESOLVED="$(https_3proxy_find_plugin PCREPlugin "${HTTPS_PCRE_PLUGIN:-}" 2>/dev/null || true)"
    HTTPS_UPSTREAM_CA_RESOLVED="$(https_3proxy_find_upstream_ca 2>/dev/null || true)"
    [ -n "$HTTPS_3PROXY_BIN_RESOLVED" ] || return 11
    [ -n "$HTTPS_SSL_PLUGIN_RESOLVED" ] || return 12
    [ -n "$HTTPS_PCRE_PLUGIN_RESOLVED" ] || return 13
    [ -n "$HTTPS_UPSTREAM_CA_RESOLVED" ] || return 14
    return 0
}

https_3proxy_render()
{
    https_3proxy_probe || return $?
    https_rules_tmp="$ADS_HTTPS_RUNTIME_DIR/request-rules.3proxy.$$"
    https_compile_request_rules "$ADS_HTTPS_RULES_FILE" "$https_rules_tmp" || { rm -f "$https_rules_tmp"; return 21; }
    https_bind="${HTTPS_PROXY_BIND:-127.0.0.1}"
    https_port="$(ads_num "${HTTPS_PROXY_PORT:-3128}" 3128)"
    https_clients="${HTTPS_ALLOWED_CLIENTS:-127.0.0.1}"
    https_maxconn="$(ads_num "${HTTPS_MAX_CONNECTIONS:-32}" 32)"
    https_valid_ip_or_host "$https_bind" || { rm -f "$https_rules_tmp"; return 22; }
    https_valid_client_acl "$https_clients" || { rm -f "$https_rules_tmp"; return 23; }
    [ "$https_port" -ge 1024 ] && [ "$https_port" -le 65535 ] || { rm -f "$https_rules_tmp"; return 24; }
    [ "$https_maxconn" -ge 1 ] && [ "$https_maxconn" -le 256 ] || { rm -f "$https_rules_tmp"; return 25; }
    [ "${HTTPS_GUARD_MODE:-explicit_proxy}" = explicit_proxy ] || { rm -f "$https_rules_tmp"; return 26; }
    {
        echo '# Generated by VWARD HTTPS Content Guard. Do not edit.'
        echo 'daemon'
        printf 'pidfile %s\n' "$ADS_HTTPS_PID_FILE"
        printf 'maxconn %s\n' "$https_maxconn"
        echo 'nscache 65536'
        echo 'timeouts 1 5 30 60 180 1800 15 60'
        if [ "$(https_bool_value "${HTTPS_DEBUG_LOG:-0}")" = 1 ]; then
            printf 'log %s D\n' "$ADS_HTTPS_LOG"
            echo 'rotate 3'
        else
            echo 'nolog'
        fi
        printf 'plugin %s ssl_plugin\n' "$HTTPS_SSL_PLUGIN_RESOLVED"
        printf 'plugin %s pcre_plugin\n' "$HTTPS_PCRE_PLUGIN_RESOLVED"
        printf 'ssl_server_ca_file %s\n' "$ADS_HTTPS_CA_CERT"
        printf 'ssl_server_ca_key %s\n' "$ADS_HTTPS_CA_KEY"
        printf 'ssl_server_key %s\n' "$ADS_HTTPS_LEAF_KEY"
        echo 'ssl_client_verify'
        printf 'ssl_client_ca_file %s\n' "$HTTPS_UPSTREAM_CA_RESOLVED"
        echo 'ssl_mitm'
        cat "$https_rules_tmp"
        echo 'auth iponly'
        printf 'allow * %s * 80,443 HTTP,HTTPS\n' "$https_clients"
        echo 'deny *'
        printf 'proxy -p%s -i%s\n' "$https_port" "$https_bind"
    } > "$ADS_HTTPS_PROVIDER_CONFIG" || { rm -f "$https_rules_tmp"; return 27; }
    rm -f "$https_rules_tmp"
    chmod 0600 "$ADS_HTTPS_PROVIDER_CONFIG" 2>/dev/null || true
    return 0
}

https_3proxy_pid_matches()
{
    p="$1"; case "$p" in ''|*[!0-9]*) return 1;; esac
    kill -0 "$p" 2>/dev/null || return 1
    proc_root="${HTTPS_PROC_ROOT:-/proc}"
    [ -r "$proc_root/$p/cmdline" ] || return 1
    cmd="$(tr '\000' ' ' < "$proc_root/$p/cmdline" 2>/dev/null)"; [ -n "$cmd" ] || return 1
    bin="${HTTPS_3PROXY_BIN_RESOLVED:-$(https_3proxy_find_bin 2>/dev/null || true)}"; [ -n "$bin" ] || return 1
    process_name="${HTTPS_3PROXY_PROCESS_NAME:-$(basename "$bin")}"; case "$process_name" in ''|*[!A-Za-z0-9_.-]*) return 1;; esac
    case "$cmd" in *"$process_name"*) return 0;; *) return 1;; esac
}

https_3proxy_start()
{
    https_3proxy_probe || return $?
    [ -r "$ADS_HTTPS_PROVIDER_CONFIG" ] || return 31
    [ ! -r "$ADS_HTTPS_PID_FILE" ] || {
        p="$(cat "$ADS_HTTPS_PID_FILE" 2>/dev/null)"
        case "$p" in ''|*[!0-9]*) ;; *) https_3proxy_pid_matches "$p" && return 0 ;; esac
        rm -f "$ADS_HTTPS_PID_FILE"
    }
    "$HTTPS_3PROXY_BIN_RESOLVED" "$ADS_HTTPS_PROVIDER_CONFIG" >/dev/null 2>&1 || return 32
    i=0
    while [ "$i" -lt 20 ]; do
        p="$(cat "$ADS_HTTPS_PID_FILE" 2>/dev/null)"
        case "$p" in ''|*[!0-9]*) ;; *) https_3proxy_pid_matches "$p" && return 0 ;; esac
        i=$((i+1)); sleep 1
    done
    return 33
}

https_3proxy_stop()
{
    p="$(cat "$ADS_HTTPS_PID_FILE" 2>/dev/null)"
    case "$p" in ''|*[!0-9]*) rm -f "$ADS_HTTPS_PID_FILE"; return 0 ;; esac
    if kill -0 "$p" 2>/dev/null; then
        https_3proxy_pid_matches "$p" || { rm -f "$ADS_HTTPS_PID_FILE"; return 43; }
        kill "$p" 2>/dev/null || return 41
        i=0
        while [ "$i" -lt 10 ] && https_3proxy_pid_matches "$p"; do i=$((i+1)); sleep 1; done
        https_3proxy_pid_matches "$p" && return 42
    fi
    rm -f "$ADS_HTTPS_PID_FILE"
    return 0
}
