server.modules = (
    "mod_cgi"
)

server.document-root = "/opt/share/keenetic-apps/www"
server.bind = "192.168.1.1"
server.port = 8088

server.pid-file = "/opt/var/run/keenetic-apps-lighttpd.pid"
server.errorlog = "/opt/var/log/keenetic-apps-lighttpd.log"

index-file.names = (
    "index.html"
)

cgi.assign = (
    ".cgi" => ""
)

mimetype.assign = (
    ".html" => "text/html",
    ".htm"  => "text/html",
    ".css"  => "text/css",
    ".js"   => "application/javascript",
    ".json" => "application/json",
    ".txt"  => "text/plain"
)
